# Copy and paste on https://dbdiagram.io/

Table Sync {
  id uuid [pk]
  title text
  description textarea [null]
  timeZone string [default: "UTC"]
  expiresAt datetime [null]
  createdAt datetime
}

Table Participant {
  id uuid [pk]
  name string
  syncId uuid [ref: > Sync.id]
  createdAt datetime
}

Table TimeOption {
  id uuid [pk]
  syncId uuid [ref: > Sync.id]
  date datetime
  startTime datetime
  endTime datetime
  // If it is null, made by host
  createdByParticipantId uuid [ref: > Participant.id, null]
  createdAt datetime
}

Table Vote {
  id uuid [pk]
  participantId uuid [ref: > Participant.id]
  timeOptionId uuid [ref: > TimeOption.id]
  createdAt datetime

  indexes {
    (participantId, timeOptionId) [unique]
  }
}